# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 5 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
gems:
  - jekyll-paginate

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Devin Young Web

description: Devin Young Blog
author:
  name: Devin Young
  email: devin@devinyoungweb.com
  github: imdevin567
  twitter: devinyoungweb
  googleplus: DevinYoungRocks
  linkedin: devinyoung
  bio: Buy me a scotch.
  email_md5: 5a8690209b6c80b2a5d8d69e6b130baf

comments:
  provider: disqus
  disqus:
    short_name: devinyoungweb

analytics:
  provider: google
  google:
    tracking_id: 'UA-37275588-1'

rss_path: feed.xml
resume_path: resume
blog_path: blog
categories_path: categories.html
tags_path: tags.html
permalink: /blog/:title

BASE_PATH:
